name: Build Forge Mod
on: [push]  # 代码变动时自动编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission
      run: chmod +x gradlew
      
    - name: Build mod
      run: ./gradlew build --no-daemon
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bonsai-mod
        path: build/libs/*.jar
