name: Download and Unzip Bonsai Mod
on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发工作流

jobs:
  unzip_mod:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库代码
        uses: actions/checkout@v4

      - name: 安装unzip工具
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: 下载bonsaitree_forge_mod.zip
        run: |
          wget "https://github.com/Atclid/atclid/raw/main/bonsaitree_forge_mod.zip" -O "bonsai_mod.zip"
          # 注意：如果文件不在main分支或根目录，请修改raw后的路径

      - name: 检查下载是否成功
        run: |
          if [ -f "bonsai_mod.zip" ]; then
            echo "文件下载成功！"
          else
            echo "错误：未找到bonsaitree_forge_mod.zip，请检查文件路径"
            exit 1
          fi

      - name: 解压zip文件
        run: |
          mkdir -p mods_extracted
          unzip bonsai_mod.zip -d mods_extracted
          echo "解压完成，文件已保存到mods_extracted目录"

      - name: 查看解压结果
        run: |
          echo "解压后的文件列表："
          ls -l mods_extracted/
