name: Unzip Mod and Commit

on:
  push:
    paths:
      - 'bonsaitree_forge_mod.zip'
  workflow_dispatch:

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予写入权限
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，允许提交

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Check if zip file exists
        id: check_file
        run: |
          if [ -f "bonsaitree_forge_mod.zip" ]; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "错误：未找到文件"
            echo "file_exists=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Unzip mod package
        if: env.file_exists == 'true'
        run: |
          mkdir -p bonsaitree_mod
          unzip bonsaitree_forge_mod.zip -d bonsaitree_mod/
          ls -R bonsaitree_mod

      - name: Commit and push changes
        if: env.file_exists == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # 检查是否有文件变更
          if [[ $(git status --porcelain) ]]; then
            git add bonsaitree_mod/
            git commit -m "自动解压模组文件"
            
            # 使用内置 token 直接推送
            git push https://github.com/${{ github.repository }}.git HEAD:main
            echo "✅ 推送成功"
          else
            echo "没有文件变更，跳过提交"
            exit 0
          fi
